def save(weights, filename='./data/perceptron.csv'):
    with open(filename, 'w') as f:
        for _ in weights:
            f.write(f"{_},")

def load(filename='./data/perceptron.csv'):
    weights = []
    with open(filename, 'r') as f:
        for _ in f:
            weights.append(float(_.strip().split(',')))
    return weights


# This code has been entirely generated by Claude Sonnet 4.5.
# I kept this commented in for reference because I lost the screenshot of the prompt
#   I used to generate it.

# def save_perceptron(weights, filename='perceptron.txt'):
#     #Save perceptron weights and bias to a file
#     with open(filename, 'w') as f:
#         # Write each weight on a new line
#         for weight in weights:
#             f.write(f"{weight}\n")
#     print(f"Perceptron saved to {filename}")

# def load_perceptron(filename='perceptron.txt'):
#     #Load perceptron weights and bias from a file
#     with open(filename, 'r') as f:
#         # Read weights
#         weights = []
#         for line in f:
#             weights.append(float(line.strip()))
#     print(f"Perceptron loaded from {filename}")
#     return weights

